common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from page1 import views
from community import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('page1/', include('page1.urls')),
    path('common/', include('common.urls')),
    # path('', views.index, name='index'),
    path('', include('community.urls')),
    path('community/', include('community.urls')), 
    path('mypage/', include('mypage.urls')),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,

)

site/config/urls.py
from django.contrib import admin
from django.urls import path, include
from module import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('module/', include('module.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from community import views
from .views import logout_view

#app_name = 'community'


urlpatterns = [
    path('', views.main_page),
    path('login.html', views.login_page, name='login'),
    path('my_page.html', views.my_page, name='my_page'),
    path('', views.main_page, name='community'),
    #path('main_page.html', auth_views.LogoutView.as_view(template_name='main_page.html'), name='main_page'),
    #path('main_page.html', auth_views.LogoutView.as_view(template_name='main_page.html'), name='main_page'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('loginok.html', views.loginok_page, name='loginok'),
    #path('logout.html/', auth_views.LogoutView.as_view(), name='logout'),
    path('my_page2.html/', views.my_page2, name='my_page2'),
    path('community/create_post/', views.create_post, name='create_post'),
    path('logout/', logout_view, name='logout'),
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #path('community/logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    path('community/post_detail/<int:pk>/', views.post_detail, name='post_detail'),
    #path('community/post_detail/<int:pk>/', views.post_detail, name='post_detail'), # 각 게시물 상세 페이지로 넘어가도록
    #nonuser_post_detail
    path('community/post/<int:pk>/', views.nonuser_post_detail, name='nonuser_post_detail'),
    
    path('add_comment/<int:pk>/', views.add_comment, name='add_comment'),
    
    path('like_post/<int:pk>/', views.like_post, name='like_post'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('delete_comment/<int:pk>/', views.delete_comment, name='delete_comment'),

]
#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

module/common/models.py
from django.db import models

# Create your models here.

site/module/models.py
from django.db import models

class Post(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject
    
class Answer(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "password1", "password2")
        

module/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "password1", "password2")
        

common/views.py
# Create your views here.
from django.shortcuts import render, redirect
from common.forms import UserForm
from django.contrib import messages

## 가입
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, '가입이 완료되었습니다. 로그인해주세요.')
            return redirect('common:login')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

module/common/views.py
# Create your views here.
from django.shortcuts import render, redirect
from common.forms import UserForm
from django.contrib import messages

## 가입
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, '가입이 완료되었습니다. 로그인해주세요.')
            return redirect('common:login')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

modulesite/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('mypage')
    else:
        form = AuthenticationForm()
    return render(request, 'login/login.html', {'form': form})

modulesite/signup/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'signup/signup.html', {'form': form})

site/common/views.py
from django.shortcuts import render, redirect
from common.forms import UserForm
from django.contrib import messages


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, '가입이 완료되었습니다. 로그인해주세요.')
            return redirect('common:login')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

site/module/views.py
from django.shortcuts import render
from django.shortcuts import render
from .models import Post


def index(request):
    post_list = Post.objects.order_by('-create_date')
    context = {'post_list': post_list}
    return render(request, 'module/index.html', context)

site/templates/common/login.html
{% extends "base.html" %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    로그인
    {% endblock %}

    {% block content %}
    <style>
        body {
            font-family: sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }

        .container {
            width: 400px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
            margin-bottom: 15px;
        }

        button {
            background-color: #000000;
            color: #fff;
            width : 100%;
            padding: 10px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    {% if messages %}
    <div class="container">
        {% for message in messages %}
            <div>{{ message }}</div>
        {% endfor %}
    {% endif %}
    </div>
    <div class="container">
        <h1>로그인</h1>
        <form method="post" action="{% url 'common:login' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="mb-3">
                <label for="username">아이디</label>
                <input type="text" class="form-control" name="username" id="username"
                    value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password">비밀번호</label>
                <input type="password" class="form-control" name="password" id="password"
                    value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <br>
            <button type="submit">로그인</button>
        </form>
        <br>
        <a href="{% url 'common:signup' %}" style="color:black">회원가입</a>
    </div>
</body>
{% endblock %}
</html>

site/templates/common/signup.html
{% extends "base.html" %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    회원가입
    {% endblock %}
    
    {% block content %} 
    <style>
        body {
            font-family: sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }

        .container {
            width: 400px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
            margin-bottom: 15px;
        }

        button {
            background-color: #000000;
            color: #fff;
            width : 100%;
            padding: 10px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }
    </style>
</head>
<body> 
    <div class="container">
        <h1>회원가입</h1>
        <form method="post" action="{% url 'common:signup' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="mb-3">
                <label for="username">아이디</label>
                <input type="text" class="form-control" name="username" id="username"
                    value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password1">비밀번호</label>
                <input type="password" class="form-control" name="password1" id="password1"
                    value="{{ form.password1.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password2">비밀번호 확인</label>
                <input type="password" class="form-control" name="password2" id="password2"
                    value="{{ form.password2.value|default_if_none:'' }}">
            </div>
            <br>
            <button type="submit">가입하기</button>
        </form>
    </div>
    {% endblock %}
</body>
</head>
</html>